# email:
#   from: %config.email.from%
#   to: %config.email.to%
#   smtp_host: %config.email.smtp_host%
#   smtp_port: %config.email.smtp_port%
#   smtp_username: %config.email.smtp_username%
#   smtp_password: %config.email.smtp_password%
#   smtp_tls: %config.email.smtp_tls%
#   template: %config.email.template%

web_server:
  bind: 0.0.0.0
  port: 5951
  web_ui: yes

templates:
  global:
    transmission:
      host: %transmission_host%
      port: %transmission_port%
      username: %transmission_username%
      password: %transmission_password%
    exists_series: '%existing_series_root_folder%{{series_name}}'

  series_eztv:
    series:
      - Supernatural
      - Doctor Who 2005:
          quality: 720p

  series_toon:
    series:
      - Gravity Falls

  series_pir8:
    series:
      - The strain
      - The Walking Dead
      - The man in the high castle
      - Una Serie Di Sfortunati Eventi
      - Mr. Robot

  series_general:
    series:
      - Sherlock:
          quality: 720p
      - White Collar:
          quality: <=720p
      - Grimm:
          quality: <=720p
      - How I met your mother:
          quality: <=720p
      - True detective:
          quality: =1080p
      - Doctor Who
      - Suits
      - Castle
      - House of cards
      - Revolution
      # - The Walking Dead:
      #     quality: <=720p
      - Resurrection
      - Hart of dixie
      - Fargo
      - The Newsroom
      - Wayward Pines
      - Zoo
      # - The strain:
      #     quality: <=720p
      - Sense 8
      - Show me a hero
      - The Shannara Chronicles
      - Orange is the new black:
          quality: hdtv <720p
      - Le regole del delitto perfetto:
          quality: <=720p
      - Outlander:
          quality: <=720p
      - Westworld:
          quality: <=720p
      - Timeless:
          quality: <=720p
      - 11.22.63

tasks:
  pir8 task:
    rss:
      url: http://www.tntvillage.scambioetico.org/rss.php?c=29&p=20
    regexp:
      reject_excluding:
        - (p|P)ir8
    template: series_pir8

  tntvillage task:
    rss:
      url: http://www.tntvillage.scambioetico.org/rss.php?c=29&p=20
      other_fields: [author]
    template: series_general
    #regexp:
    #  reject:
    #    - (s|S)ub\s+(i|I)ta

  toon task:
    rss:
      url: http://www.tntvillage.scambioetico.org/rss.php?c=8&p=20
    template: series_toon

  # Show registered on http://showrss.info
  # Doctor Who 2005
  # Supernatural
  showrss task:
    rss:
      url: http://showrss.info/user/131356.rss?magnets=true&namespaces=true&name=null&quality=null&re=null
    template: series_eztv

schedules:
  - tasks: '*'
    interval:
      hours: 1
