templates:
  series_general:
    transmission:
      host: 127.0.0.1
      port: 9091
      username: fabrizio
      password: ramiel
    exists_series: '/media/5381b885-61ca-44fd-943b-af33cd9e95e2/Video/SerieTv/{{series_name}}'
    series:
      - Supernatural:
          quality: 720p
      - Sherlock:
          quality: 720p
      - White Collar:
          quality: <=720p
      - Grimm:
          quality: <=720p
      - Castle:
          quality: <=720p
      - How I met your mother:
          quality: <=720p
      - Elementary:
          quality: <=720p
      - Suits:
          quality: <=720p
      - House of cards
      - Revolution
      - Doctor Who
      - The Walking Dead
      - Resurrection

tasks:
  tntvillage task:
    rss: 
      url: http://www.tntvillage.scambioetico.org/rss.php?c=29&p=20
      other_fields: [author]
    template: series_general
    #regexp:
    #  reject:
    #    - (s|S)ub\s+(i|I)ta

  ezsupernatural task:
    rss:
      url: http://ezrss.it/search/?mode=simple&show_name=Supernatural&mode=rss
    template: series_general

schedules:
  - tasks: '*'
    interval:
      hours: 1
