email:
  from: %config.email.from%
  to: %config.email.to%
  smtp_host: %config.email.smtp_host%
  smtp_port: %config.email.smtp_port%
  smtp_username: %config.email.smtp_username%
  smtp_password: %config.email.smtp_password%
  smtp_tls: %config.email.smtp_tls%
  template: %config.email.template%

templates:
  series_general:
    transmission:
      host: %transmission_host%
      port: 9091
      username: fabrizio
      password: ramiel
    exists_series: '%existing_series_root_folder%{{series_name}}'
    series:
      - Supernatural:
          quality: 720p
      - Sherlock:
          quality: 720p
      - White Collar:
          quality: <=720p
      - Grimm:
          quality: <=720p
      - How I met your mother:
          quality: <=720p
      - Suits
      - Castle
      - Elementary
      - House of cards
      - Revolution
      - Doctor Who
      - The Walking Dead
      - Resurrection

tasks:
  tntvillage task:
    rss: 
      url: http://www.tntvillage.scambioetico.org/rss.php?c=29&p=20
      other_fields: [author]
    template: series_general
    #regexp:
    #  reject:
    #    - (s|S)ub\s+(i|I)ta

  #ezsupernatural task:
  #  rss:
  #    url: http://ezrss.it/search/?mode=simple&show_name=Supernatural&mode=rss
  #  template: series_general
  #  email:
  #    from: tvseries@ramielcreations.com
  #    to: fabrizio.ruggeri@gmail.com
  #    smtp_host: srv-hp11.netsons.net
  #    smtp_port: 465
  #    smtp_username: tvseries@ramielcreations.com
  #    smtp_password: tvs3r13s|
  #    smtp_tls: no
  #    template: html

schedules:
  - tasks: '*'
    interval:
      hours: 1
